dependencies:
- name: docker-2048
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: jx-golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
